### ISSUE TITLE
Замечания по работе #3.1. Добавляем новые блоки

### ISSUE THREAD

**Issue by Und3rMySk1n** [TooHotMan/fe_course#1]
1. Неправильная работа со сбросом потока страницы (clear). Из-за этого блок с классом top_menu нулевой высоты, main_container_content не принял высоту вложенного в него контента. movies_description нулевой высоты.

2. All movies должна быть ссылкой или button'ом. При наведении на нее курсор должен меняться на палец (pointer).

3. В названиях изображений присутствуют заглавные буквы, это не соответствует соглашению о наименовании файлов.

**Comment by saintiago** [comment]
```css
.taxi_driver_description,
.angry_man_description,
.will_description,
.lll_description
{
    width: 285px;
    height: auto;
    float: left;
}
```
Это 4 одинаковых по стилю блока. 
Должен быть один класс для их стилизации.

Учесть на всей странице.

**Comment by saintiago** [comment]
### *необязательно*

```html
<a id="link_about_me"><h1 class="some_text_name_title">Grigor Ogannisian</h1></a>
<div class="rectangle"></div>
```
Сделать зеленую полоску (*rectangle*) под h1 через псевдоэлемент [:after](http://htmlbook.ru/css/after).
```css
some_text_name_title:after
```
Это позволит избавится от элемента оформления в html разметке и добавлять такую полоску автоматически при использовании класса заголовка.

**Comment by saintiago** [comment]
### Именования

```html
<a id="link_about_me"><h1 class="some_text_name_title">Grigor Ogannisian</h1></a>
...
<span class="some_favorite_title">My favorite movies</span>
```
Очень плохие названия.

При использовании ```<a ...></a>``` для якоря не надо оборачивать в ```<a>``` элемент ```h1```, достаточно поставить ```<a ...></a>``` перед ```h1```
```html
<a id="link_about_me"></a>
<h1 class="some_text_name_title">Grigor Ogannisian</h1>
```

**Comment by saintiago** [comment]
```css
.list
{
    line-height: 36px;
    margin-left: 21px;
    margin-top: 12px;
}
```
Для размещения буллетов/номеров внутри блока вместо ```margin-left``` надо использовать ```list-style-position: inside``` (http://htmlbook.ru/css/list-style-position)
