### ISSUE TITLE
Замечания по работе #3.2. Форма обратной связи

### ISSUE THREAD

**Issue by Und3rMySk1n** [TooHotMan/fe_course#2]
1. Нет стрелки вниз у select'а.

2. У input'ов должен быть внутренний отступ слева и справа. Вводимый текст не должен прижиматься к краю поля ввода. Заодно можно указать для полей ввода такой же шрифт, как для select'а. Сейчас шрифт при вводе слишком мелкий. Это же относится к textarea.

3. При наведении курсора на select,текст радиокнопки (male/female) и кнопку submit, курсор должен меняться на палец (pointer).

**Comment by Saintiago** [comment]
```css
.taxi_driver_description,
.angry_man_description,
.will_description,
.lll_description
{
    width: 285px;
    height: auto;
    float: left;
}
```
Это 4 одинаковых по стилю блока. 
Должен быть один класс для их стилизации.

**Comment by Saintiago** [comment]
*необязательно*

```html
<a id="link_about_me"><h1 class="some_text_name_title">Grigor Ogannisian</h1></a>
<div class="rectangle"></div>
```
Сделать зеленую полоску (*rectangle*) под h1 через псевдоэлемент [:after](http://htmlbook.ru/css/after).
```
some_text_name_title:after
```
Это позволит избавится от элемента оформления в html разметке и добавлять такую полоску автоматически при использовании класса заголовка.

**Comment by Saintiago** [comment]
### Именования

```html
<a id="link_about_me"><h1 class="some_text_name_title">Grigor Ogannisian</h1></a>
```
some_text_name_title - очень плохое название.

При использовании ```<a ...></a>``` для якоря не надо оборачивать в ```<a>``` элемент *h1*, достаточно поставить ```<a ...></a> перед *h1*
```html
<a id="link_about_me"></a>
<h1 class="some_text_name_title">Grigor Ogannisian</h1>
```

**Comment by Saintiago** [comment]
```css
.list
{
    line-height: 36px;
    margin-left: 21px;
    margin-top: 12px;
}
```
Для размещения буллетов/номеров внутри блока вместо ```margin-left``` надо использовать ```list-style-position: inside``` (http://htmlbook.ru/css/list-style-position)
